#!/bin/sh
PREFIX=
[ -f /var/jb/Library/LaunchDaemons/com.xsxs18.tweakpilotd.plist ] && PREFIX=/var/jb
launchctl unload "$PREFIX/Library/LaunchDaemons/com.xsxs18.tweakpilotd.plist" >/dev/null 2>&1
[ "$1" = remove ] && rm -f "$PREFIX/usr/libexec/tweakpilot/token"
exit 0
